name: Render manual.pdf
on: push

permissions:
  contents: write

jobs:
  render-manual:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name : Install fonts
        run: | 
          mkdir fonts
          cd fonts
          wget https://github.com/alerque/libertinus/releases/download/v7.051/Libertinus-7.051.zip
          unzip Libertinus-7.051.zip
          mv Libertinus-7.051/static/OTF/LibertinusMath-Regular.otf ~/.local/share/fonts/
          wget https://github.com/georgd/EB-Garamond/releases/download/nightly/EBGaramond.zip
          unzip EBGaramond.zip
          mv *.otf ~/.local/share/fonts/
          fc-cache -f
          cd ..
          rm -Rf fonts
      - name: Setup Typst
        uses: typst-community/setup-typst@v5
      - name: Change Import-Paths and Font Name for CI
        run: | 
          sed -i 's|@preview/ma-template:[^"]*|../lib.typ|g' template/*.typ
          sed -i 's|EB Garamond|EB Garamond 12|g' template/main.typ
      - name: Compile Document
        run: | 
          cd template
          typst compile --root .. main.typ ../docs/manual.pdf
          cd ..
      - name: Commit and Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          git add docs/manual.pdf
          # Nur committen, wenn es tatsächlich Änderungen gibt
          git diff --quiet && git diff --staged --quiet || (git commit -m "Automatische Aktualisierung des Manuals" && git push)

